version: "3.9"

services:
    todo:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: "postgres:13.2-alpine"
        ports:
            - "5432:5432"
        volumes:
            - ./pg_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=dev_only
            - POSTGRES_DB=postgres
