FROM python:3.9.2-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt .
RUN python -m pip install --upgrade pip 
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app

EXPOSE 8000/tcp

CMD python manage.py runserver 0:8000
